
###
GET http://localhost:8080/questions/all

###
GET http://localhost:8080/questions/sort/title?sort=asc

###
GET http://localhost:8080/questions/sort/title?sort=desc

###
GET http://localhost:8080/questions/sort/date?sort=asc

###
GET http://localhost:8080/questions/sort/date?sort=desc

###
GET http://localhost:8080/questions/sort/answer?sort=asc

###
GET http://localhost:8080/questions/sort/answer?sort=desc


###
GET http://localhost:8080/questions/2

###
GET http://localhost:8080/answers/all/2


###
POST http://localhost:8080/answers/
Content-Type: application/json

{
  "answer_detail": "I am not sure.",
  "question_id": "2",
  "user_id": 1
}

###
GET http://localhost:8080/users/login/whateverBe

###
GET http://localhost:8080/users/login/beanAddict96


###
POST http://localhost:4000/api/cities/64136c7e74fb3da9ac934e0c/sights
Content-Type: application/json

{
  "sight": "Times Square"
}


###
DELETE http://localhost:4000/api/cities/64136c7e74fb3da9ac934e0c/sights
Content-Type: application/json

{
  "sight": "Times Square"
}


###
GET http://localhost:4000/api/bucketlist


###
GET http://localhost:4000/api/bucketlist?cityid=641191d7e1d28d34f42a742e


###
PATCH http://localhost:4000/api/bucketlist/64136dca698ebec0206628ec


###
GET http://localhost:4000/api/contacts


###
POST http://localhost:4000/api/contacts
Content-Type: application/json

{
  "firstName": "Jakab",
  "lastName": "Gipsz",
  "email": "email@valami.hu",
  "phone": "06-20-1234567",
  "message": "Hello, your page is awesome",
  "subscribe": true
}


###
GET http://localhost:4000/api/cities?reviews=asc

